### ISSUE TITLE
Variants that automatically switch between latte and the dark variants

### ISSUE THREAD

**Issue by TamasBarta** [catppuccin/spicetify#29]
The CSS could use media queries to determine if it should apply the light or the dark colours. I achieved it once with another theme, but I was just copy pasting from another site.

I'd very much prefer such a variant, because now I'm manually switching all the time between latte and mocha, and Spotify is basically a web app, so it can have such a theme.

**Comment by aidan-gibson** [comment]
This bandaid for your shell config helps. I don't want it to automatically run when macOS changes colors because it would stop music currently playing (as spotify reboots). There is definitely a way to live-update themes without restarting (https://github.com/FlafyDev/spotify-css-editor) but no extension currently exists (that I could find).
```zsh
light="catppuccin-latte"
dark="catppuccin-mocha"

alias spotl="spicetify config current_theme ${light} && spicetify config extensions ${dark}.js- && spicetify config extensions ${light}.js &&spicetify apply enable-devtools"
alias spotd="spicetify config current_theme ${dark} && spicetify config extensions ${light}.js- && spicetify config extensions ${dark}.js &&spicetify apply enable-devtools"

spot(){
    current_theme=$(spicetify config current_theme)
    if [[ "$current_theme" == "$dark" ]]; then
        spotl
    else
        spotd
    fi
}
```

**Comment by ohitstom** [comment]
I'll look into implementing this soon now that we have a settings menu, would be pretty simple!

**Comment by ohitstom** [comment]
There is some unfortunate news, Spotify passes in a force-dark-mode flag during its chromium compilation stage.
This means there is no way for us to know what the current system theme is with js OR css.

The only current solution is manually patching the executable by hand, im not sure where to go from here... Maybe a button in the topbar to swap between the two? it wouldnt be automatic but it would be something, what do you think?

**Comment by TamasBarta** [comment]
It feels starting to get overengineered with the buttons and all that (at least for a first/most basic version of this). I'm not sure about if the forced dark mode is Windows specific, but on macOS I could manage to use the OS settings with media queries, using the method suggested [here](https://github.com/spicetify/spicetify-cli/issues/423#issuecomment-785224958).

Here's my example version for the green colour scheme alternating between latte and mocha:

<details><summary>Put this to the end of the `user.css` of a Catppuccin theme</summary>

```css
:root {
    --spice-shadow: #e6e9ef;
    --spice-button-active: #7c7f93;
    --spice-notification-error: #d20f39;
    --spice-highlight-elevated: #2a2a2a;
    --spice-highlight: #1a1a1a;
    --spice-button-disabled: #9ca0b0;
    --spice-tab-active: #ddc0da;
    --spice-main-elevated: #242424;
    --spice-accent: #fae3b0;
    --spice-misc: #acb0be;
    --spice-button: #8c8fa1;
    --spice-subtext: #4c4f69;
    --spice-main: #eff1f5;
    --spice-sidebar: #e6e9ef;
    --spice-selected-row: #acb0be;
    --spice-text: #40a02b;
    --spice-card: #ccd0da;
    --spice-player: #dce0e8;
    --spice-equalizer: #40a02b;
    --spice-notification: #ddc0da;
    --spice-rgb-shadow: 230,233,239;
    --spice-rgb-button-active: 124,127,147;
    --spice-rgb-notification-error: 210,15,57;
    --spice-rgb-highlight-elevated: 42,42,42;
    --spice-rgb-highlight: 26,26,26;
    --spice-rgb-button-disabled: 156,160,176;
    --spice-rgb-tab-active: 221,192,218;
    --spice-rgb-main-elevated: 36,36,36;
    --spice-rgb-accent: 250,227,176;
    --spice-rgb-misc: 172,176,190;
    --spice-rgb-button: 140,143,161;
    --spice-rgb-subtext: 76,79,105;
    --spice-rgb-main: 239,241,245;
    --spice-rgb-sidebar: 230,233,239;
    --spice-rgb-selected-row: 172,176,190;
    --spice-rgb-text: 64,160,43;
    --spice-rgb-card: 204,208,218;
    --spice-rgb-player: 220,224,232;
    --spice-rgb-equalizer: 64,160,43;
    --spice-rgb-notification: 221,192,218;
}

@media (prefers-color-scheme: dark) {
    :root {
        --spice-selected-row: #585b70;
        --spice-notification-error: #f28fad;
        --spice-main: #1e1e2e;
        --spice-button-disabled: #6e6c7e;
        --spice-button: #7f849c;
        --spice-text: #a6e3a1;
        --spice-button-active: #9399b2;
        --spice-highlight: #1a1a1a;
        --spice-player: #11111b;
        --spice-misc: #585b70;
        --spice-shadow: #181825;
        --spice-tab-active: #313244;
        --spice-highlight-elevated: #2a2a2a;
        --spice-notification: #313244;
        --spice-card: #313244;
        --spice-subtext: #cdd6f4;
        --spice-sidebar: #181825;
        --spice-equalizer: #a6e3a1;
        --spice-main-elevated: #242424;
        --spice-rgb-selected-row: 88,91,112;
        --spice-rgb-notification-error: 242,143,173;
        --spice-rgb-main: 30,30,46;
        --spice-rgb-button-disabled: 110,108,126;
        --spice-rgb-button: 127,132,156;
        --spice-rgb-text: 166,227,161;
        --spice-rgb-button-active: 147,153,178;
        --spice-rgb-highlight: 26,26,26;
        --spice-rgb-player: 17,17,27;
        --spice-rgb-misc: 88,91,112;
        --spice-rgb-shadow: 24,24,37;
        --spice-rgb-tab-active: 49,50,68;
        --spice-rgb-highlight-elevated: 42,42,42;
        --spice-rgb-notification: 49,50,68;
        --spice-rgb-card: 49,50,68;
        --spice-rgb-subtext: 205,214,244;
        --spice-rgb-sidebar: 24,24,37;
        --spice-rgb-equalizer: 166,227,161;
        --spice-rgb-main-elevated: 36,36,36;
    }
}
```

</details>

Of course this may not be completely sufficient, as the colour schemes differ by darkness level. Rather I wanted to demonstrate that probably media queries will do the trick. If not, I'd suggest coming up with something on the Spicetify side, since the ini with the variable names may limit this functionality for theme authors, and in that case, I would endorse patching it on every theme's side. The issue I linked was closed, but we may ask for reopening it.
